### ISSUE TITLE
Some tickets aren't being returned

### ISSUE THREAD

**Issue by cybersimon** [markfinger/assembla#7] opened 2012-12-12 23:36 UTC
I have found that for some reason the odd ticket doesn't get returned when this call is made:
space.tickets()

Will investigate this when I get a chance. For my reference, NFSA ticket 1206 doesn't get returned.

**Comment by markfinger** [comment] 2012-12-13 22:29
I think this might be due to assembla paginating some results, which the wrapper was never tested against.

**Comment by markfinger** [comment] 2012-12-31 06:06
Assuming this was caused by pagination issues, this has been fixed in the version 2 codebase. 
Relevant commit is 20ce46fbbdbfc42204a7f1b31a4c05f48869953f.

**Closed as completed by markfinger** 2012-12-31 06:06 UTC
